// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	SignIn *SignInResult `json:"signIn"`
	SignUp *SignUpResult `json:"signUp"`
}

type NewTodo struct {
	Text string `json:"text"`
}

type NewUser struct {
	Name     string `json:"name" validate:"required,min=2,max=128"`
	Email    string `json:"email" validate:"required,email,max=255"`
	Password string `json:"password" validate:"required,min=6,max=64"`
}

type SignInResult struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type SignUpResult struct {
	IsCreated bool `json:"isCreated"`
}
